import type { BotDefinition } from "./types";

export const registeredBots: BotDefinition[] = [
  {
    id: "galerazo",
    name: "Galerazo Bot",
    initials: "GA",
    description: "Automatización de comunidad, respuestas y eventos programados.",
    status: "degraded",
    statusLabel: "Ver estado",
    provider: "Google Compute Engine",
    transport: "gcp-iap",
    environment: "producción · remoto",
    host: "galerazo-prod",
    version: "ver imagen desplegada",
    commit: "remoto",
    updatedAt: "consultar estado",
    capabilities: ["status", "logs", "triggers", "credentials", "deploy"],
  },
  {
    id: "spider",
    name: "Spider Tracker",
    initials: "ST",
    description: "Monitoreo periódico de publicaciones y cambios de contenido.",
    status: "offline",
    statusLabel: "Sin conexión",
    provider: "Adaptador pendiente",
    transport: "ssh",
    environment: "sin conexión real",
    host: "sin configurar",
    version: "—",
    commit: "—",
    updatedAt: "sin conexión",
    capabilities: [],
  },
  {
    id: "reshare",
    name: "Reshare Stories",
    initials: "RS",
    description: "Redistribución automática de historias y piezas aprobadas.",
    status: "offline",
    statusLabel: "Sin conexión",
    provider: "Adaptador pendiente",
    transport: "railway",
    environment: "sin conexión real",
    host: "sin configurar",
    version: "—",
    commit: "—",
    updatedAt: "sin conexión",
    capabilities: [],
  },
];
