import type { BotDefinition } from "./types";

export const demoBots: BotDefinition[] = [
  {
    id: "galerazo",
    name: "Galerazo Bot",
    initials: "GA",
    description: "Automatización de comunidad, respuestas y eventos programados.",
    status: "online",
    statusLabel: "Operativo",
    provider: "Google Compute Engine",
    transport: "gcp-iap",
    environment: "producción · demo",
    host: "galerazo-prod-01",
    version: "v2.8.1",
    commit: "a19f32c",
    updatedAt: "hace 18 s",
    capabilities: ["status", "logs", "sql", "triggers", "credentials", "deploy"],
    metrics: [
      { label: "Uptime", value: "12d 4h", detail: "sin reinicios", tone: "good" },
      { label: "CPU", value: "8%", detail: "promedio 5 min" },
      { label: "Memoria", value: "312 MB", detail: "de 1 GB" },
      { label: "Disco", value: "3.8 GB", detail: "de 10 GB" },
      { label: "Base SQLite", value: "46.2 MB", detail: "query_only" },
      { label: "Eventos hoy", value: "1.284", detail: "+11% vs. ayer", tone: "good" },
    ],
    logs: [
      { id: "g1", timestamp: "14:32:08", level: "info", source: "scheduler", message: "Checkpoint diario completado en 184 ms" },
      { id: "g2", timestamp: "14:31:44", level: "info", source: "telegram", message: "Update 934812 procesado · chat -1001842" },
      { id: "g3", timestamp: "14:30:17", level: "warning", source: "rate-limit", message: "Reintento 1/3 luego de respuesta 429" },
      { id: "g4", timestamp: "14:29:51", level: "info", source: "trigger", message: "Trigger “fixture” ejecutado en 42 ms" },
      { id: "g5", timestamp: "14:27:02", level: "error", source: "media", message: "Miniatura remota no disponible; se usó fallback" },
      { id: "g6", timestamp: "14:25:39", level: "info", source: "database", message: "WAL checkpoint: 147 páginas consolidadas" },
    ],
    triggers: [
      {
        id: "t1",
        name: "Próximo partido",
        phrase: "/fixture",
        response: "Envía el próximo partido confirmado con la placa animada.",
        enabled: true,
        hits: 318,
        lastHit: "hace 2 min",
        createdAt: "18 jul 2026 · 21:43",
        createdBy: { id: "tg-184921", displayName: "Mateo Sosa", username: "mateososa" },
        chat: { id: "-1001842001", title: "La Banda de Galerazo", platform: "telegram" },
        media: {
          kind: "video",
          filename: "proximo-partido.webm",
          mimeType: "video/webm",
          source: "generated-demo",
        },
      },
      {
        id: "t2",
        name: "Tabla actual",
        phrase: "/tabla",
        response: "Publica posiciones y diferencia de gol.",
        enabled: true,
        hits: 191,
        lastHit: "hace 14 min",
        createdAt: "17 jul 2026 · 10:22",
        createdBy: { id: "tg-772104", displayName: "Paula Ríos", username: "paularios" },
        chat: { id: "-1001842001", title: "La Banda de Galerazo", platform: "telegram" },
        media: {
          kind: "audio",
          filename: "tabla-actual.wav",
          mimeType: "audio/wav",
          source: "generated-demo",
        },
      },
      {
        id: "t3",
        name: "Bienvenida",
        phrase: "nuevo miembro",
        response: "Saludo y reglas del grupo.",
        enabled: true,
        hits: 62,
        lastHit: "hace 3 h",
        createdAt: "11 jul 2026 · 08:10",
        createdBy: { id: "tg-005811", displayName: "Admin Galerazo", username: "admin_galerazo" },
        chat: { id: "-1007765110", title: "Galerazo Oficial", platform: "telegram" },
      },
      {
        id: "t4",
        name: "Encuesta postpartido",
        phrase: "fin del partido",
        response: "Publica una placa con la votación del jugador destacado.",
        enabled: false,
        hits: 27,
        lastHit: "hace 6 d",
        createdAt: "03 jul 2026 · 23:48",
        createdBy: { id: "tg-493820", displayName: "Nico Alvarez", username: "nicoalvarez" },
        chat: { id: "-1001842001", title: "La Banda de Galerazo", platform: "telegram" },
        media: {
          kind: "image",
          filename: "jugador-destacado.png",
          mimeType: "image/png",
          source: "generated-demo",
        },
      },
      {
        id: "t5",
        name: "Gol celebrado",
        phrase: "goooool",
        response: "Responde con el sticker estático de celebración.",
        enabled: true,
        hits: 144,
        lastHit: "hace 32 min",
        createdAt: "15 jul 2026 · 19:06",
        createdBy: { id: "tg-631982", displayName: "Cami Ferreyra", username: "camiferreyra" },
        chat: { id: "-1001842001", title: "La Banda de Galerazo", platform: "telegram" },
        media: {
          kind: "sticker",
          filename: "gol-galerazo.webp",
          mimeType: "image/webp",
          source: "generated-demo",
        },
      },
      {
        id: "t6",
        name: "Bandera animada",
        phrase: "dale galerazo",
        response: "Responde con un sticker animado en WebM.",
        enabled: true,
        hits: 88,
        lastHit: "hace 1 h",
        createdAt: "14 jul 2026 · 16:31",
        createdBy: { id: "tg-338104", displayName: "Lola Méndez", username: "lolamendez" },
        chat: { id: "-1007765110", title: "Galerazo Oficial", platform: "telegram" },
        media: {
          kind: "sticker",
          filename: "bandera-galerazo.webm",
          mimeType: "video/webm",
          source: "generated-demo",
        },
      },
      {
        id: "t7",
        name: "Escudo giratorio",
        phrase: "somos galerazo",
        response: "Responde con un sticker vectorial animado de Telegram.",
        enabled: true,
        hits: 51,
        lastHit: "hace 4 h",
        createdAt: "12 jul 2026 · 12:54",
        createdBy: { id: "tg-904477", displayName: "Fede Luna", username: "fedeluna" },
        chat: { id: "-1007765110", title: "Galerazo Oficial", platform: "telegram" },
        media: {
          kind: "sticker",
          filename: "escudo-galerazo.tgs",
          mimeType: "application/x-tgsticker",
          source: "generated-demo",
        },
      },
    ],
    queryRows: [
      { trigger: "/fixture", ejecuciones: 318, errores: 1, ultima_vez: "2026-07-20 14:29" },
      { trigger: "/tabla", ejecuciones: 191, errores: 0, ultima_vez: "2026-07-20 14:18" },
      { trigger: "bienvenida", ejecuciones: 62, errores: 0, ultima_vez: "2026-07-20 11:07" },
    ],
  },
  {
    id: "spider",
    name: "Spider Tracker",
    initials: "ST",
    description: "Monitoreo periódico de publicaciones y cambios de contenido.",
    status: "degraded",
    statusLabel: "Con alertas",
    provider: "VPS · Hetzner",
    transport: "ssh",
    environment: "producción · demo",
    host: "spider-eu-02",
    version: "v1.4.0",
    commit: "f091b8e",
    updatedAt: "hace 1 min",
    capabilities: ["status", "logs", "sql"],
    metrics: [
      { label: "Uptime", value: "3d 18h", detail: "último deploy" },
      { label: "CPU", value: "71%", detail: "pico sostenido", tone: "warning" },
      { label: "Memoria", value: "694 MB", detail: "de 1 GB", tone: "warning" },
      { label: "Disco", value: "12.1 GB", detail: "de 20 GB" },
      { label: "Base SQLite", value: "118 MB", detail: "query_only" },
      { label: "Capturas hoy", value: "426", detail: "17 pendientes", tone: "warning" },
    ],
    logs: [
      { id: "s1", timestamp: "14:31:11", level: "warning", source: "crawler", message: "Cola con 17 trabajos pendientes" },
      { id: "s2", timestamp: "14:29:20", level: "info", source: "worker-2", message: "Lote de 25 URLs completado" },
      { id: "s3", timestamp: "14:24:09", level: "error", source: "parser", message: "Selector principal ausente en fuente 12" },
      { id: "s4", timestamp: "14:21:38", level: "info", source: "database", message: "Persistidos 42 cambios" },
    ],
    triggers: [],
    queryRows: [
      { fuente: "portal-a", pendientes: 9, ultimo_ok: "2026-07-20 14:29" },
      { fuente: "portal-b", pendientes: 8, ultimo_ok: "2026-07-20 14:22" },
    ],
  },
  {
    id: "reshare",
    name: "Reshare Stories",
    initials: "RS",
    description: "Redistribución automática de historias y piezas aprobadas.",
    status: "offline",
    statusLabel: "Detenido",
    provider: "Railway",
    transport: "railway",
    environment: "staging · demo",
    host: "reshare-staging",
    version: "v0.9.6",
    commit: "c72e113",
    updatedAt: "hace 22 min",
    capabilities: ["status", "logs"],
    metrics: [
      { label: "Uptime", value: "—", detail: "servicio detenido" },
      { label: "CPU", value: "0%", detail: "sin proceso" },
      { label: "Memoria", value: "0 MB", detail: "sin proceso" },
      { label: "Disco", value: "1.2 GB", detail: "volumen persistente" },
      { label: "Base SQLite", value: "—", detail: "sin acceso" },
      { label: "Publicaciones", value: "0", detail: "hoy" },
    ],
    logs: [
      { id: "r1", timestamp: "14:10:03", level: "info", source: "service", message: "Proceso detenido manualmente" },
      { id: "r2", timestamp: "14:09:58", level: "info", source: "shutdown", message: "Conexiones cerradas correctamente" },
    ],
    triggers: [],
    queryRows: [],
  },
];
