import type { BotDefinition } from "./types";

export const demoBots: BotDefinition[] = [
  {
    id: "galerazo",
    name: "Galerazo Bot",
    initials: "GA",
    description: "Automatización de comunidad, respuestas y eventos programados.",
    status: "degraded",
    statusLabel: "Ver estado",
    provider: "Google Compute Engine",
    transport: "gcp-iap",
    environment: "producción · remoto",
    host: "galerazo-prod",
    version: "ver imagen desplegada",
    commit: "remoto",
    updatedAt: "consultar estado",
    capabilities: ["status", "logs", "triggers", "credentials", "deploy"],
    metrics: [],
    logs: [],
    triggers: [],
    queryRows: [],
  },
  {
    id: "spider",
    name: "Spider Tracker",
    initials: "ST",
    description: "Monitoreo periódico de publicaciones y cambios de contenido.",
    status: "degraded",
    statusLabel: "Con alertas",
    provider: "VPS · Hetzner",
    transport: "ssh",
    environment: "producción · demo",
    host: "spider-eu-02",
    version: "v1.4.0",
    commit: "f091b8e",
    updatedAt: "hace 1 min",
    capabilities: ["status", "logs", "sql"],
    metrics: [
      { label: "Uptime", value: "3d 18h", detail: "último deploy" },
      { label: "CPU", value: "71%", detail: "pico sostenido", tone: "warning" },
      { label: "Memoria", value: "694 MB", detail: "de 1 GB", tone: "warning" },
      { label: "Disco", value: "12.1 GB", detail: "de 20 GB" },
      { label: "Base SQLite", value: "118 MB", detail: "query_only" },
      { label: "Capturas hoy", value: "426", detail: "17 pendientes", tone: "warning" },
    ],
    logs: [
      { id: "s1", timestamp: "14:31:11", level: "warning", source: "crawler", message: "Cola con 17 trabajos pendientes" },
      { id: "s2", timestamp: "14:29:20", level: "info", source: "worker-2", message: "Lote de 25 URLs completado" },
      { id: "s3", timestamp: "14:24:09", level: "error", source: "parser", message: "Selector principal ausente en fuente 12" },
      { id: "s4", timestamp: "14:21:38", level: "info", source: "database", message: "Persistidos 42 cambios" },
    ],
    triggers: [],
    queryRows: [
      { fuente: "portal-a", pendientes: 9, ultimo_ok: "2026-07-20 14:29" },
      { fuente: "portal-b", pendientes: 8, ultimo_ok: "2026-07-20 14:22" },
    ],
  },
  {
    id: "reshare",
    name: "Reshare Stories",
    initials: "RS",
    description: "Redistribución automática de historias y piezas aprobadas.",
    status: "offline",
    statusLabel: "Detenido",
    provider: "Railway",
    transport: "railway",
    environment: "staging · demo",
    host: "reshare-staging",
    version: "v0.9.6",
    commit: "c72e113",
    updatedAt: "hace 22 min",
    capabilities: ["status", "logs"],
    metrics: [
      { label: "Uptime", value: "—", detail: "servicio detenido" },
      { label: "CPU", value: "0%", detail: "sin proceso" },
      { label: "Memoria", value: "0 MB", detail: "sin proceso" },
      { label: "Disco", value: "1.2 GB", detail: "volumen persistente" },
      { label: "Base SQLite", value: "—", detail: "sin acceso" },
      { label: "Publicaciones", value: "0", detail: "hoy" },
    ],
    logs: [
      { id: "r1", timestamp: "14:10:03", level: "info", source: "service", message: "Proceso detenido manualmente" },
      { id: "r2", timestamp: "14:09:58", level: "info", source: "shutdown", message: "Conexiones cerradas correctamente" },
    ],
    triggers: [],
    queryRows: [],
  },
];
